[package]
name = "razerd"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
razer-proto = { path = "../razer-proto" }
razer-devices = { path = "../razer-devices" }
razer-hid = { path = "../razer-hid" }

[[bin]]
name = "razerd"
path = "src/main.rs"
